### PR TITLE
Bumping Rasterific dependency

### PR DESCRIPTION
**Pull request by Twinside**
I will release soon a new version of Rasterific with a new feature you may find handy:

  * PDF export (without image handling for now, will land in a minor).

I've succesfully compiled diagrams-rasterific 1.3.1.0 with Rasterific 0.6

### CODE REVIEW

**Comment by jeffreyrosenbluth** [comment]
PDF - nice !

**Comment by snoyberg** [comment]
@jeffreyrosenbluth Can you ping me when this is released to Hackage so I can update Stackage?

**Comment by jeffreyrosenbluth** [comment]
@snoyberg, sure thing.

**Comment by jeffreyrosenbluth** [comment]
@Twinside 
Do you intend 0.6 to work with ghc 7.6.3.
I ran into this problem building:

src/Graphics/Rasterific/MicroPdf.hs:28:8:
    Could not find module `Data.ByteString.Builder'
    Perhaps you meant
      Data.ByteString.Lazy.Builder (from bytestring-0.10.0.2)
      Data.ByteString.Unsafe (from bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.

**Comment by Twinside** [comment]
0.6.1 works with GHC 7.6.3, it was due to a bad lower bound on bytestring.

**Comment by jeffreyrosenbluth** [comment]
so i guess i need a lower bound of 0.6.1

**Comment by byorgey** [comment]
@jeffreyrosenbluth if you want to be fancy you can also say something like >= 0.5 && < 0.6 || >= 0.6.1 && < 0.7

**Comment by byorgey** [comment]
But there's probably not much need for such fanciness here, I doubt anyone will have a problem with just installing the latest version of Rasterific.

**Comment by jeffreyrosenbluth** [comment]
@snoyberg 
Uploaded to hackage as 1.3.1.1

**Pull request merged**
